spring.application.name=mars-visualizer

# Chemin des fichiers NetCDF MEAN
netcdf.mean.path=C:/Users/User/Desktop/mars-data/mean

# Chemin des fichiers NetCDF individuels
netcdf.individual.path=C:/Users/User/Desktop/mars-data/individual

# Port du serveur
server.port=8080

# Logs
logging.level.com.mars.visualizer=DEBUG
logging.level.org.springframework.web=INFO

# DevTools (rechargement automatique)
spring.devtools.restart.enabled=true