spring.application.name=mars-visualizer

# Chemin des fichiers NetCDF MEAN
netcdf.mean.path=C:/Users/User/Desktop/mars-data/mean

# Chemin des fichiers NetCDF individuels
netcdf.individual.path=C:/Users/User/Desktop/mars-data/individual

# Premier MY connu dans le dossier individual/
# (les annees suivantes sont detectees automatiquement par scan)
netcdf.individual.my_base=34

# Port du serveur
server.port=8080

# Logs compact
spring.main.banner-mode=off
logging.pattern.console=%d{HH:mm:ss.SSS} %5p [%15.15t] %-40.40logger{39} : %m%n
logging.level.com.mars.visualizer=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.boot=WARN
logging.level.org.apache.catalina=WARN

# DevTools (rechargement automatique)
spring.devtools.restart.enabled=true